# weave
project = 'organization/project'
dataset_ref = 'dataset-name:latest'
evaluate_prompt_ref = 'prompt-name:latest'

# model
api_type = 'openai' # 'openai', 'bedrock', 'google'
predict_model_name = 'model-name'
evaluate_model_name = 'model-name'

# execution
max_retries = 5
initial_retry_delay = 5
max_retry_delay = 30